# Generated by Django 3.1.4 on 2021-03-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank='True', null='True', upload_to='media'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_id',
            field=models.IntegerField(default=11),
        ),
    ]
